// netlify/functions/hubspot-tasks.mjs
// GET /api/hubspot-tasks?email=X
// Returns open HubSpot CRM tasks assigned to the user.

const OWNER_MAP = {
  'jessica@happenventures.com': 673782347,
    'ivan@happenventures.com':    233808806,
      'danny@happenventures.com':   87891263,
        'milos@happenventures.com':   414691200,
          'mario@happenventures.com':   320265772,
          };

          const USER_INFO = {
            'jessica@happenventures.com': { name: 'Jess Gonzalez', role: 'CEO' },
              'ivan@happenventures.com':    { name: 'Ivan',           role: 'CGO Sales' },
                'danny@happenventures.com':   { name: 'Danny',          role: 'Donations PM' },
                  'milos@happenventures.com':   { name: 'Milos',          role: 'Recycle PM' },
                    'mario@happenventures.com':   { name: 'Mario',          role: 'Junk PM' },
                    };

                    export default async (req) => {
                      try {
                          const url = new URL(req.url);
                              const email = (url.searchParams.get('email') || '').toLowerCase();

                                  if (!email) return json({ error: 'Missing email param' }, 400);

                                      const ownerId = OWNER_MAP[email];
                                          if (!ownerId) return json({ error: `HubSpot tasks not configured for: ${email}` }, 404);

                                              const token = Netlify.env.get('HUBSPOT_PRIVATE_APP_TOKEN') || Netlify.env.get('HUBSPOT_API_KEY');
                                                  if (!token) return json({ error: 'HubSpot token not configured' }, 500);

                                                      const userInfo = USER_INFO[email];

                                                          const searchBody = {
                                                                filterGroups: [{
                                                                        filters: [
                                                                                  { propertyName: 'hubspot_owner_id', operator: 'EQ',  value: String(ownerId) },
                                                                                            { propertyName: 'hs_task_status',   operator: 'NEQ', value: 'COMPLETED' },
                                                                                                    ],
                                                                                                          }],
                                                                                                                properties: [
                                                                                                                        'hs_task_subject',
                                                                                                                                'hs_task_body',
                                                                                                                                        'hs_task_status',
                                                                                                                                                'hs_task_priority',
                                                                                                                                                        'hs_timestamp',
                                                                                                                                                                'hs_task_completion_date',
                                                                                                                                                                        'hs_task_type',
                                                                                                                                                                              ],
                                                                                                                                                                                    limit: 100,
                                                                                                                                                                                          sorts: [{ propertyName: 'hs_timestamp', direction: 'ASCENDING' }],
                                                                                                                                                                                              };

                                                                                                                                                                                                  const res = await fetch('https://api.hubapi.com/crm/v3/objects/tasks/search', {
                                                                                                                                                                                                        method: 'POST',
                                                                                                                                                                                                              headers: {
                                                                                                                                                                                                                      'Authorization': `Bearer ${token}`,
                                                                                                                                                                                                                              'Content-Type': 'application/json',
                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                          body: JSON.stringify(searchBody),
                                                                                                                                                                                                                                              });

                                                                                                                                                                                                                                                  if (!res.ok) {
                                                                                                                                                                                                                                                        const text = await res.text();
                                                                                                                                                                                                                                                              return json({ error: 'HubSpot API failed', status: res.status, detail: text }, 502);
                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                      const data = await res.json();
                                                                                                                                                                                                                                                                          const today = new Date(); today.setHours(0, 0, 0, 0);

                                                                                                                                                                                                                                                                              const tasks = (data.results || []).map(r => {
                                                                                                                                                                                                                                                                                    const p = r.properties || {};
                                                                                                                                                                                                                                                                                          const dueDate = p.hs_timestamp
                                                                                                                                                                                                                                                                                                  ? new Date(p.hs_timestamp).toISOString().slice(0, 10)
                                                                                                                                                                                                                                                                                                          : null;
                                                                                                                                                                                                                                                                                                                const due = dueDate ? new Date(dueDate + 'T00:00:00') : null;
                                                                                                                                                                                                                                                                                                                      const isOverdue = !!(due && due < today);

                                                                                                                                                                                                                                                                                                                            return {
                                                                                                                                                                                                                                                                                                                                    id: r.id,
                                                                                                                                                                                                                                                                                                                                            name: p.hs_task_subject || '(untitled)',
                                                                                                                                                                                                                                                                                                                                                    description: p.hs_task_body || '',
                                                                                                                                                                                                                                                                                                                                                            status: statusLabel(p.hs_task_status),
                                                                                                                                                                                                                                                                                                                                                                    priority: priorityLabel(p.hs_task_priority),
                                                                                                                                                                                                                                                                                                                                                                            type: p.hs_task_type || null,
                                                                                                                                                                                                                                                                                                                                                                                    dueDate,
                                                                                                                                                                                                                                                                                                                                                                                            overdue: isOverdue,
                                                                                                                                                                                                                                                                                                                                                                                                    department: null,
                                                                                                                                                                                                                                                                                                                                                                                                            airtableUrl: `https://app.hubspot.com/tasks/${r.id}`,
                                                                                                                                                                                                                                                                                                                                                                                                                  };
                                                                                                                                                                                                                                                                                                                                                                                                                      });

                                                                                                                                                                                                                                                                                                                                                                                                                          const stats = {
                                                                                                                                                                                                                                                                                                                                                                                                                                total: tasks.length,
                                                                                                                                                                                                                                                                                                                                                                                                                                      overdue: tasks.filter(t => t.overdue).length,
                                                                                                                                                                                                                                                                                                                                                                                                                                            dueToday: tasks.filter(t => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (!t.dueDate || t.overdue) return false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                            return new Date(t.dueDate + 'T00:00:00').getTime() === today.getTime();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }).length,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        doneThisWeek: 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return json({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      user: { email, name: userInfo.name, role: userInfo.role },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            count: tasks.length,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  stats,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        tasks,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              source: 'hubspot',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    fetchedAt: new Date().toISOString(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return json({ error: err.message, stack: err.stack }, 500);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                function statusLabel(s) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  switch (s) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      case 'NOT_STARTED': return 'Open';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          case 'IN_PROGRESS': return 'In Progress';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              case 'WAITING':     return 'Waiting';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  case 'DEFERRED':    return 'Deferred';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      case 'COMPLETED':   return 'Completed';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          default:            return s || 'Open';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            function priorityLabel(p) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              switch (p) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  case 'HIGH':   return 'High';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      case 'MEDIUM': return 'Medium';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          case 'LOW':    return 'Low';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              default:       return null;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                function json(body, status = 200) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return new Response(JSON.stringify(body), {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      status,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          headers: { 'Content-Type': 'application/json', 'Cache-Control': 'no-store' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            export const config = { path: '/api/hubspot-tasks' };